export const CORE_URL = "../core/ffmpeg-core.js";

export const FFMessageType = {
  LOAD: "LOAD",
  EXEC: "EXEC",
  FFPROBE: "FFPROBE",
  WRITE_FILE: "WRITE_FILE",
  READ_FILE: "READ_FILE",
  DELETE_FILE: "DELETE_FILE",
  RENAME: "RENAME",
  CREATE_DIR: "CREATE_DIR",
  LIST_DIR: "LIST_DIR",
  DELETE_DIR: "DELETE_DIR",
  MOUNT: "MOUNT",
  UNMOUNT: "UNMOUNT",
  ERROR: "ERROR",
  LOG: "LOG",
  PROGRESS: "PROGRESS",
};
