export const FFMessageType = {
  LOAD: "LOAD",
  EXEC: "EXEC",
  WRITE_FILE: "WRITE_FILE",
  READ_FILE: "READ_FILE",
  DELETE_FILE: "DELETE_FILE",
  RENAME: "RENAME",
  CREATE_DIR: "CREATE_DIR",
  LIST_DIR: "LIST_DIR",
  DELETE_DIR: "DELETE_DIR",
  ERROR: "ERROR",
  LOG: "LOG",
  PROGRESS: "PROGRESS",
  DONE: "DONE",
};

export const ErrorMessage = {
  UNKNOWN_MESSAGE_TYPE: "UNKNOWN_MESSAGE_TYPE",
  NOT_LOADED: "NOT_LOADED",
  TERMINATED: "TERMINATED",
  IMPORT_FAILURE: "IMPORT_FAILURE",
};
