export const ERROR_UNKNOWN_MESSAGE_TYPE = "UNKNOWN_MESSAGE_TYPE";

export const ERROR_NOT_LOADED = "NOT_LOADED";

export const ERROR_TERMINATED = "TERMINATED";

export const ERROR_IMPORT_FAILURE = "IMPORT_FAILURE";
